### PR TITLE
Secondary Nav Loading Fix

### LINKED ISSUE #549: TypeError: null is not an object (evaluating 'e.title')
https://sentry.io/newspring-church/apollos/issues/539308490/

```
TypeError: null is not an object (evaluating 'e.title')
  at default (/Users/isaac.hardy/NewSpring/Apollos/src/@utils/content/share.js:6:16)
  at onPress (/Users/isaac.hardy/NewSpring/Apollos/src/@ui/SecondaryNav/index.js:12:12)
  at onPress (/Users/isaac.hardy/NewSpring/Apollos/src/@ui/NativeWebRouter/Link.js:59:20)
  at touchableHandlePress ([native code])
  at _performSideEffectsForTransition ([native code])
...
(23 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by richarddubay**
Fixes #549 

This attempts to load the secondary nav (think "like and share" nav) only AFTER the content loads. This should fix errors where there is no content to share.

## Creator

- [ ] Build relevant tests if any apply
- [ ] Ensure there are no new warnings
- [ ] Upload an animated GIF showcasing the solution (if it applies)
- [ ] Set a relevant reviewer

## Reviewer

- [ ] Run `test` and make sure all tests pass
- [ ] Review function and form on iOS
- [ ] Review function and form on Android
- [ ] Review function and form on Web
- [ ] Review new test logic

### CODE REVIEW

**Comment by conrad-vanl** [comment]
@richarddubay this PR got a little out of hand I assume to using prettifier. Could you point me to the relevant lines of code in this PR to look at?

File: src/series/Sermon.js [hunk 1]
```diff
@@ -71,7 +71,7 @@ const Sermon = enhance(
         </ContentView>
         <HorizontalTileFeed content={children} isLoading={isLoading} showTileMeta />
       </ScrollView>
-      <SecondaryNav>
+      <SecondaryNav isLoading={isLoading}>
```
Comment (conrad-vanl) [inline src/series/Sermon.js]: This is the way I'd do it 👍

File: src/@ui/SecondaryNav/index.js [hunk 2]
```diff
@@ -27,14 +27,16 @@ const SecondaryNav = ({
...
+  isLoading = false,
+}) =>
+  !isLoading && (
+    <TabBar>
+      {backButton ? (
+        <Link pop to={backTo} icon={backButtonIcon} onPress={onBackPress} replace={onBackReplace} />
+      ) : null}
+      {children}
+    </TabBar>
+  );
```
Comment (richarddubay) [inline src/@ui/SecondaryNav/index.js]: I added a `isLoading` prop to the Secondary Nav here.

File: src/articles/Single.js [hunk 3]
```diff
@@ -20,38 +20,38 @@ const enhance = compose(
...
-      <SecondaryNav>
-        <ShareLink id={id} />
-        <Like id={id} isLiked={isLiked} />
-      </SecondaryNav>
-    </MediaQuery>
-  </BackgroundView>
-));
+      </ScrollView>
+      <MediaQuery maxWidth="md">
+        <SecondaryNav isLoading={isLoading}>
```
Comment (richarddubay) [inline src/articles/Single.js]: Then I passed that prop to the secondary nav here. I did this part in multiple places.

File: src/group-finder/GroupSingle.js [hunk 4]
```diff
@@ -95,162 +90,193 @@ GroupInfo.propTypes = {
...
+                    },
+                  ]}
+                  linkToGroup={false}
+                />
+              </Right>
+            </MediaQuery>
+          ) : null}
+        </FlexedSideBySideView>
+        <MediaQuery maxWidth="md">
+          <SecondaryNav isLoading={isLoading}>
```
Comment (richarddubay) [inline src/group-finder/GroupSingle.js]: Here.

File: src/music/Playlist.js [hunk 5]
```diff
@@ -16,52 +16,48 @@ const enhance = compose(
...
+            isLoading={isLoading}
+            title={title}
+            artist="NewSpring"
+            albumImage={getAlbumImageSource(images)}
+            blurredImage={getBlurredImageSource(images)}
+          />
+        }
+      />
+      <MediaQuery maxWidth="md">
+        <SecondaryNav isLoading={isLoading}>
```
Comment (richarddubay) [inline src/music/Playlist.js]: and here.

File: src/news/Single.js [hunk 6]
```diff
@@ -20,35 +20,33 @@ const enhance = compose(
...
+      <Header titleText="News" backButton />
+      <ScrollView>
+        <ContentView isLoading={isLoading} {...otherContentProps}>
+          <Title>{startCase(toLower(title))}</Title>
+          <ByLine authors={authors} />
+          <HTMLView>{body}</HTMLView>
+        </ContentView>
+      </ScrollView>
+      <MediaQuery maxWidth="md">
+        <SecondaryNav isLoading={isLoading}>
```
Comment (richarddubay) [inline src/news/Single.js]: and here

File: src/series/Sermon.js (hunk 1 above)
Comment (richarddubay) [inline src/series/Sermon.js]: and here

File: src/series/Single.js [hunk 7]
```diff
@@ -48,56 +48,56 @@ const StyledButton = styled(({ theme }) => ({
...
         !isLoading && <RelatedContent tags={tags} excludedIds={[id]} />}
-    </ScrollView>
-    <SecondaryNav>
-      <ShareLink id={id} />
-      <Like id={id} isLiked={isLiked} />
-    </SecondaryNav>
-  </BackgroundView>
-));
+      </ScrollView>
+      <SecondaryNav isLoading={isLoading}>
```
Comment (richarddubay) [inline src/series/Single.js]: and here

File: src/stories/Single.js [hunk 8]
```diff
@@ -21,36 +21,35 @@ const enhance = compose(
...
+      <ScrollView>
+        <ContentView isLoading={isLoading} {...otherContentProps}>
+          <Title>{startCase(toLower(title))}</Title>
+          <ByLine authors={authors} />
+          <HTMLView>{body}</HTMLView>
+        </ContentView>
+        <RelatedContent tags={tags} excludedIds={[id]} />
+      </ScrollView>
+      <MediaQuery maxWidth="md">
+        <SecondaryNav isLoading={isLoading}>
```
Comment (richarddubay) [inline src/stories/Single.js]: and here

File: src/studies/Entry/index.js [hunk 9]
```diff
@@ -41,58 +41,57 @@ const enhance = compose(
...
+              isLoading,
+            })(DevotionalTab),
+            scripture: withProps({
+              scripture,
+              entryData: children,
+              isLoading,
+            })(ScriptureTab),
+          })}
+        />
+        <SecondaryNav isLoading={isLoading}>
```
Comment (richarddubay) [inline src/studies/Entry/index.js]: and here.

File: src/studies/Single.js [hunk 10]
```diff
@@ -37,46 +37,40 @@ const enhance = compose(
...
         !isLoading && <RelatedContent tags={tags} excludedIds={[id]} />}
-    </ScrollView>
-    <SecondaryNav>
-      <ShareLink id={id} />
-      <Like id={id} isLiked={isLiked} />
-    </SecondaryNav>
-  </BackgroundView>
-));
+      </ScrollView>
+      <SecondaryNav isLoading={isLoading}>
```
Comment (richarddubay) [inline src/studies/Single.js]: and finally here.

**Comment by richarddubay** [comment]
@conrad-vanl Yep! I added comments to pretty much all of the lines that I changed. Sorry about all the `prettier` stuff.

File: src/@ui/SecondaryNav/index.js (hunk 2 above)
Comment (conrad-vanl) [reply src/@ui/SecondaryNav/index.js]: This is Ok, but be careful returning a conditional expression in a render function like this. You're better off doing something like:

```
!isLoading ? (<MyComponent ..../>) : null
```

because then you explicitly return `null` instead of `!isLoading`. The problem with returning a conditional expression like this is that you don't really want to render `!isLoading`, you want to render `null`. In this case, `!isLoading` would resolve to `false` and nothing would be rendered, which is why this is Ok. But say you omitted the `!` ... and did something like:

```
conditionalProp && <MyComponent />
```

If `conditionalProp` is ever an empty string, that's a falsey value, but still a string. So an empty string would be returned. React-Native would then try and render an empty string - which is invalid unless wrapped inside of a `<Text>` component. Therefore, you'd get a RSOD. You could do:

```
!!conditionalProp && <MyComponent />
```

to make sure you're always returning a component or a boolean, but nonetheless: if you don't want to render something based off of a prop, it's better to make sure you return `null` as that is handled more consistently within react. Using ternaries like this (`someProp ? <RenderThis /> : null`) is the standard we've adopted in this project to assert render-ability.

Comment (richarddubay) [reply src/@ui/SecondaryNav/index.js]: @conrad-vanl This is super helpful and makes a ton of sense! I'll make that change.
