### PR TITLE
fix empty array error and implement basic aspect ratio sorting

### LINKED ISSUE #349: Look into image cropping on content cards
> all the images for the devos and studies and maybe also sermon entries don't looked scaled right either

I believe the reference here is that Card images are being cropped - ie...`ConnectedImage` isn't showing the square image. This could be solved by tweaking the graphql queries, sorting the images better, or something else.

### PR DESCRIPTION
**Pull request by conrad-vanl**
Fixes #349 as well as an issue affecting current master builds where if a content item had no images, would result in a crashed app.

## Creator

- [x] Build relevant tests if any apply
- [x] Ensure there are no new warnings
- [ ] Upload an animated GIF showcasing the solution (if it applies)
- [x] Set a relevant reviewer

## Reviewer

- [x] Run `test` and make sure all tests pass
- [x] Review function and form on iOS
- [ ] Review function and form on Android
- [x] Review function and form on Web
- [x] Review new test logic

### CODE REVIEW

File: src/@utils/content/getItemImages.js [hunk 1]
```diff
@@ -4,7 +4,17 @@ const getItemImages = (item) => {
...
+  // FWIW, `ConnectedImage` will sort out which image is best to use from a resolution
+  // perspective, which is why we just kind of blindly push 1:1 images to the front,
+  // as it doesn't consider aspect ratio, just resolution.
+  images = [].concat(images).sort((a, b) => { // make sort pure
+    if (a && b && a.fileLabel === b.fileLabel) return 0;
+    if (a && a.fileLabel === '1:1') return -1;
+    if (b && b.fileLabel === '1:1') return 1;
+    return 0;
+  });
+  return images;
```
Comment (conrad-vanl) [inline src/@utils/content/getItemImages.js]: Basically - the error on master was the short circuit we had originally implemented to just return the first image url. This is no longer needed as `ConnectedImage` now supports an opaque data type (array, object, etc) instead of just a url string. 

Secondly, added this sort function so that we prioritize displaying of square images (not all content items have square images so we have to ask for both from heighliner). This fixes #349
